name: ci

on: [push]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: docker.pkg.github.com/luca-rand/docker-run-rs/run:c4785c3ca9605efaf7833bc922a622a125fad045
        ports:
          - 27017:27017
          - 27018:27018
          - 27019:27019
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go mod download
      - name: Test
        run: go test
      - name: Build example
        working-directory: ./example
        run: |
          go build -v .
          ./example
